Feat: 🧪  End to end parent login signup tests (#45)
* e2e

* test1

* signup works

* e2e works on parent

* minor fixes

* adding login flow to e2e

* to fail workflow

* now with the fix

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -41,9 +41,9 @@ jobs:
           echo "# Test Results! 🚀" >> $GITHUB_STEP_SUMMARY
           node api-test.js || passed="false"
           if [[ -n "$passed" ]]; then
-            echo "API test failed! ❌" >> $GITHUB_STEP_SUMMARY
+            echo "__API test failed!__ ❌" >> $GITHUB_STEP_SUMMARY
           else
-            echo "API test passed! ✅" >> $GITHUB_STEP_SUMMARY
+            echo "__API test passed!__ ✅" >> $GITHUB_STEP_SUMMARY
           fi
           cat output.txt >> $GITHUB_STEP_SUMMARY || echo "no output.txt"          
           rm output.txt || echo "no output"
@@ -55,9 +55,23 @@ jobs:
           passed=""
           node browser-test.js || passed="false"
           if [[ -n "$passed" ]]; then
-            echo "Browser test failed! ❌" >> $GITHUB_STEP_SUMMARY
+            echo "__Browser test failed!__ ❌" >> $GITHUB_STEP_SUMMARY
           else
-            echo "Browser test passed! ✅" >> $GITHUB_STEP_SUMMARY
+            echo "__Browser test passed!__ ✅" >> $GITHUB_STEP_SUMMARY
+          fi
+          cat output.txt >> $GITHUB_STEP_SUMMARY || echo "no output.txt"
+          rm output.txt || echo "no output"
+          echo "passed=$passed" >> $GITHUB_OUTPUT
+      - name: parent e2e
+        id: parent_signup_login
+        working-directory: ./test
+        run: |
+          passed=""
+          node login-test.js || passed="false"
+          if [[ -n "$passed" ]]; then
+            echo "__Parent signup & Login test failed!__ ❌" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "__Parent signup & Login test passed!__ ✅" >> $GITHUB_STEP_SUMMARY
           fi
           cat output.txt >> $GITHUB_STEP_SUMMARY || echo "no output.txt"
           rm output.txt || echo "no output"
@@ -67,7 +81,8 @@ jobs:
           docker compose down
           api=${{ steps.api_test.outputs.passed }}
           ui=${{ steps.ui_test.outputs.passed }}
-          if [[ -n "$api" ]] || [[ -n "$ui" ]]; then
+          login=${{ steps.parent_signup_login.outputs.passed }}
+          if [[ -n "$api" ]] || [[ -n "$ui" ]] || [[ -n "$login" ]]; then
             echo "not all test passed, failing the workflow"
             exit 1
           else
